// Typed API access. Types come only from ./schema (generated by `npm run gen:api`);
// requests go through ./http, hooks live in ./hooks.
export type { paths, components } from './schema'
export { api } from './http'
export { ApiError, describeError } from './errors'
