"""Seed and transcript validator (ticket T10).

Implements docs/synthetic-data-spec.md "Validation checks" plus the structural rules the
spec fixes elsewhere (counts, id prefixes, dates against `settings.demo_today`, money as
integer USD, story beats B1-B6). It is READ-ONLY: it never edits or rewrites a transcript.
A failing generated transcript is regenerated by generate.py; the hand-edited live-demo
draft is reported separately and never touched.

Usage (from the repo root or backend/):
    cd backend && uv run python ../data/scripts/validate.py
Exit code 0 only if the seed JSON and all 15 generated transcripts pass.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

_HERE = Path(__file__).resolve().parent
_BACKEND = _HERE.parent.parent / "backend"
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

SEED_DIR = _HERE.parent / "seed"
TRANSCRIPTS_DIR = SEED_DIR / "transcripts"

LIVE_MEETING_ID = "m6_finedge"
DEFAULT_WORDS = (400, 6000)  # spoken words: minimum 400; 6,000 is only a runaway-output cap
LIVE_WORDS = (600, 800)  # spec: "Live demo meeting" (about 600-800 words)
DEFAULT_DURATION_MINUTES = (20, 40)  # spec: generation rule 6
EXPECTED_MEETINGS = 17
EXPECTED_ACCOUNTS = 4
EXPECTED_CONTACTS = 13
EXPECTED_BEATS = {"B1", "B2", "B3", "B4", "B5", "B6"}
MEETING_ID_RE = re.compile(r"^[mnov]\d_(finedge|nimbus|veda|orbit)$")

LINE_RE = re.compile(
    r"^\[(\d{4}-\d{2}-\d{2})T(\d{2}):(\d{2}):(\d{2})\+05:30\] ([^()]+?) \(([^()]+)\): (.+)$"
)
PRICING_DECK_RE = re.compile(r"pricing deck", re.IGNORECASE)
DECK_RECEIVED_RE = re.compile(r"\breceived\b|\bgot\b|thanks for", re.IGNORECASE)


@dataclass
class Seed:
    company: dict[str, Any]
    accounts: list[dict[str, Any]]
    contacts: list[dict[str, Any]]
    meetings: list[dict[str, Any]]
    beats: dict[str, dict[str, Any]]  # meeting_id -> beats.json entry
    beat_defs: list[dict[str, Any]]

    def meeting(self, meeting_id: str) -> dict[str, Any]:
        return next(m for m in self.meetings if m["id"] == meeting_id)

    def contact(self, contact_id: str) -> dict[str, Any]:
        return next(c for c in self.contacts if c["id"] == contact_id)


@dataclass
class Report:
    seed_problems: list[str] = field(default_factory=list)
    per_meeting: dict[str, list[str]] = field(default_factory=dict)  # generated transcripts
    cross_problems: list[str] = field(default_factory=list)
    draft_problems: list[str] = field(default_factory=list)  # live-demo draft (m6), separate
    draft_present: bool = False
    missing: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        """True when the seed, cross-meeting rules and every generated transcript pass."""
        return (
            not self.seed_problems
            and not self.cross_problems
            and not self.missing
            and all(not p for p in self.per_meeting.values())
        )


def load_seed(seed_dir: Path = SEED_DIR) -> Seed:
    def load(name: str) -> Any:
        with (seed_dir / name).open(encoding="utf-8") as fh:
            return json.load(fh)

    beats_doc = load("beats.json")
    return Seed(
        company=load("company.json"),
        accounts=load("accounts.json"),
        contacts=load("contacts.json"),
        meetings=load("meetings.json"),
        beats={e["meeting_id"]: e for e in beats_doc["meetings"]},
        beat_defs=beats_doc["beats"],
    )


# --------------------------------------------------------------------------- transcripts


@dataclass
class Utterance:
    day: str
    seconds: int
    speaker: str
    role: str
    text: str


def parse_transcript(text: str) -> tuple[list[Utterance], list[str]]:
    """Parse the one-utterance-per-line format. Returns (utterances, bad line descriptions)."""
    utterances: list[Utterance] = []
    bad: list[str] = []
    for number, line in enumerate(text.splitlines(), start=1):
        if not line.strip():
            continue
        match = LINE_RE.match(line)
        if not match:
            bad.append(f"line {number}")
            continue
        day, hh, mm, ss, speaker, role, words = match.groups()
        utterances.append(
            Utterance(day, int(hh) * 3600 + int(mm) * 60 + int(ss), speaker.strip(), role, words)
        )
    return utterances, bad


def spoken_words(text: str) -> int:
    """Spoken-word count: words in utterance text only (no timestamps or speaker labels)."""
    utterances, _ = parse_transcript(text)
    return sum(len(u.text.split()) for u in utterances)


def _term_regex(term: str) -> re.Pattern[str]:
    return re.compile(r"(?<!\w)" + re.escape(term) + r"(?!\w)", re.IGNORECASE)


def check_transcript(
    seed: Seed,
    meeting: dict[str, Any],
    text: str,
    *,
    words: tuple[int, int],
    duration: tuple[int, int] | None,
) -> list[str]:
    """Per-transcript checks from the spec. Returns human-readable problems (empty = pass)."""
    problems: list[str] = []
    utterances, bad = parse_transcript(text)
    if bad:
        shown = ", ".join(bad[:5]) + (" ..." if len(bad) > 5 else "")
        problems.append(
            f"format: {len(bad)} line(s) do not match the transcript line format ({shown})"
        )
    if not utterances:
        problems.append("format: no utterances found")
        return problems

    attendee_names = {seed.contact(c)["name"] for c in meeting["attendees"]}
    seen: set[str] = set()
    for u in utterances:
        if u.speaker not in attendee_names and u.speaker not in seen:
            problems.append(f"speaker: {u.speaker!r} is not an attendee of {meeting['id']}")
        seen.add(u.speaker)

    wrong_days = {u.day for u in utterances if u.day != meeting["date"]}
    if wrong_days:
        problems.append(
            f"timestamps: date {sorted(wrong_days)} differs from meeting date {meeting['date']}"
        )
    for prev, cur in zip(utterances, utterances[1:], strict=False):
        if cur.seconds <= prev.seconds:
            problems.append("timestamps: do not strictly increase line by line")
            break

    if duration is not None:
        minutes = (utterances[-1].seconds - utterances[0].seconds) / 60
        if not duration[0] <= minutes <= duration[1]:
            problems.append(
                f"duration: {minutes:.0f} min of timestamps, expected {duration[0]}-{duration[1]}"
            )

    count = sum(len(u.text.split()) for u in utterances)  # spoken words only
    if not words[0] <= count <= words[1]:
        problems.append(f"word count: {count} words, expected {words[0]}-{words[1]}")

    spoken = "\n".join(u.text for u in utterances)
    entry = seed.beats.get(meeting["id"], {"required_facts": [], "forbidden": []})
    for fact in entry["required_facts"]:
        for pattern in fact["must_match"]:
            if not re.search(pattern, spoken, re.IGNORECASE):
                problems.append(
                    f"fact {fact['id']}: pattern {pattern!r} not found ({fact['text']})"
                )
    for term in entry["forbidden"]:
        if _term_regex(term).search(spoken):
            problems.append(f"forbidden string present: {term!r}")

    if meeting["date"] < _live_date(seed):
        for u in utterances:
            if PRICING_DECK_RE.search(u.text) and DECK_RECEIVED_RE.search(u.text):
                problems.append(
                    "pricing deck: mentioned as received/got/thanks-for before the live meeting"
                )
                break
    return problems


def _live_date(seed: Seed) -> str:
    return str(seed.meeting(LIVE_MEETING_ID)["date"])


# --------------------------------------------------------------------------- cross-meeting


def _next_meeting_with_beats(seed: Seed, meeting: dict[str, Any]) -> dict[str, Any] | None:
    later = [
        m
        for m in seed.meetings
        if m["account_id"] == meeting["account_id"]
        and m["date"] > meeting["date"]
        and m["id"] in seed.beats
    ]
    return min(later, key=lambda m: m["date"]) if later else None


def validate_cross(seed: Seed, transcripts: dict[str, str], *, demo_today: date) -> list[str]:
    """Promise acknowledgement rule and story-beat planting."""
    problems: list[str] = []
    for meeting in seed.meetings:
        entry = seed.beats.get(meeting["id"])
        if entry is None:
            continue
        for fact in entry["required_facts"]:
            if "promise" not in fact["id"] or fact.get("beat") == "B1":
                continue
            nxt = _next_meeting_with_beats(seed, meeting)
            key = fact["must_match"][0]
            acks = (
                [
                    f
                    for f in seed.beats[nxt["id"]]["required_facts"]
                    if f["id"].endswith("_ack") and f["must_match"][0] == key
                ]
                if nxt
                else []
            )
            if not acks:
                problems.append(
                    f"promise {fact['id']} ({meeting['id']}) is not acknowledged in a later "
                    f"meeting of the same account"
                )
    for beat in seed.beat_defs:
        for planted in beat["planted_in"]:
            entry = seed.beats.get(planted)
            tagged = [
                f for f in (entry or {}).get("required_facts", []) if f.get("beat") == beat["id"]
            ]
            if not tagged:
                problems.append(f"beat {beat['id']}: no tagged fact in {planted}")
            if (
                planted != LIVE_MEETING_ID
                and planted in {m["id"] for m in seed.meetings}
                and (seed.meeting(planted)["status"] == "done")
                and transcripts
                and planted not in transcripts
            ):
                problems.append(f"beat {beat['id']}: transcript for {planted} is missing")
    return problems


# --------------------------------------------------------------------------- seed structure


def _is_int_usd(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def validate_seed(seed: Seed, *, demo_today: date, strict_counts: bool = True) -> list[str]:
    problems: list[str] = []
    if strict_counts:
        if len(seed.meetings) != EXPECTED_MEETINGS:
            problems.append(f"expected {EXPECTED_MEETINGS} meetings, found {len(seed.meetings)}")
        if len(seed.accounts) != EXPECTED_ACCOUNTS:
            problems.append(f"expected {EXPECTED_ACCOUNTS} accounts, found {len(seed.accounts)}")
        if len(seed.contacts) != EXPECTED_CONTACTS:
            problems.append(f"expected {EXPECTED_CONTACTS} contacts, found {len(seed.contacts)}")
        counts: dict[str, int] = defaultdict(int)
        for m in seed.meetings:
            counts[m["account_id"]] += 1
        if counts and {"acc_finedge": 6, "acc_nimbus": 4, "acc_veda": 4, "acc_orbit": 3} != dict(
            counts
        ):
            problems.append(f"meetings per account differ from the spec: {dict(counts)}")

    account_ids = {a["id"] for a in seed.accounts}
    contact_ids = {c["id"] for c in seed.contacts}
    for a in seed.accounts:
        if not a["id"].startswith("acc_"):
            problems.append(f"account id {a['id']!r} lacks the acc_ prefix")
        if not _is_int_usd(a.get("deal_value_usd")):
            problems.append(f"account {a['id']}: deal_value_usd must be integer USD")
    for c in seed.contacts:
        if not c["id"].startswith("c_"):
            problems.append(f"contact id {c['id']!r} lacks the c_ prefix")
    vendor = seed.company.get("vendor", {})
    for plan in vendor.get("plans", []):
        if not _is_int_usd(plan.get("price_usd_per_year")):
            problems.append(f"plan {plan.get('name')}: price must be integer USD")
    if vendor.get("pilot") and not _is_int_usd(vendor["pilot"].get("price_usd")):
        problems.append("pilot price must be integer USD")

    for m in seed.meetings:
        mid = m["id"]
        if strict_counts and not MEETING_ID_RE.match(mid):
            problems.append(f"meeting id {mid!r} does not follow the <letter><n>_<account> prefix")
        if m["account_id"] not in account_ids:
            problems.append(f"{mid}: unknown account {m['account_id']}")
        for attendee in m["attendees"]:
            if attendee not in contact_ids:
                problems.append(f"{mid}: unknown attendee {attendee}")
        try:
            when = date.fromisoformat(m["date"])
        except ValueError:
            problems.append(f"{mid}: date {m['date']!r} is not ISO")
            continue
        if m["status"] == "done" and when > demo_today:
            problems.append(f"{mid}: status done but dated after demo_today {demo_today}")
        if m["status"] == "upcoming" and when <= demo_today:
            problems.append(f"{mid}: status upcoming but not after demo_today {demo_today}")

    seen_beats = {b["id"] for b in seed.beat_defs}
    if strict_counts and seen_beats != EXPECTED_BEATS:
        problems.append(f"beats B1-B6 expected, found {sorted(seen_beats)}")
    for mid, entry in seed.beats.items():
        try:
            meeting = seed.meeting(mid)
        except StopIteration:
            problems.append(f"beats.json references unknown meeting {mid}")
            continue
        for fact in entry["required_facts"]:
            if fact["speaker"] not in meeting["attendees"]:
                problems.append(
                    f"{mid}: fact {fact['id']} speaker {fact['speaker']} not an attendee"
                )
            for pattern in fact["must_match"]:
                try:
                    re.compile(pattern)
                except re.error:
                    problems.append(f"{mid}: fact {fact['id']} has an invalid regex {pattern!r}")
    return problems


# --------------------------------------------------------------------------- orchestration


def validate_all_texts(
    seed: Seed, texts: dict[str, str], *, demo_today: date, strict_counts: bool = False
) -> Report:
    """Validate the seed plus the given transcripts (meeting_id -> text)."""
    report = Report()
    report.seed_problems = validate_seed(seed, demo_today=demo_today, strict_counts=strict_counts)
    report.cross_problems = validate_cross(seed, texts, demo_today=demo_today)
    for meeting in seed.meetings:
        mid = meeting["id"]
        if mid not in seed.beats:
            continue  # upcoming meetings without a transcript (V4)
        if mid == LIVE_MEETING_ID:
            if mid in texts:
                report.draft_present = True
                report.draft_problems = check_transcript(
                    seed, meeting, texts[mid], words=LIVE_WORDS, duration=None
                )
            continue
        if mid not in texts:
            report.missing.append(mid)
            continue
        report.per_meeting[mid] = check_transcript(
            seed, meeting, texts[mid], words=DEFAULT_WORDS, duration=DEFAULT_DURATION_MINUTES
        )
    return report


def transcript_filename(meeting: dict[str, Any]) -> str:
    """`m1_finedge` + "Discovery" -> `m1_finedge_discovery.txt`; the live meeting is `_live`."""
    if meeting["id"] == LIVE_MEETING_ID:
        return f"{LIVE_MEETING_ID}_live.txt"
    slug = re.sub(r"[^a-z0-9]+", "_", meeting["title"].lower()).strip("_")
    return f"{meeting['id']}_{slug}.txt"


def read_transcripts(seed: Seed, transcripts_dir: Path) -> dict[str, str]:
    """Map meeting id to text for every transcript file present (read-only)."""
    texts: dict[str, str] = {}
    for meeting in seed.meetings:
        path = transcripts_dir / transcript_filename(meeting)
        if path.exists():
            texts[meeting["id"]] = path.read_text(encoding="utf-8")
    return texts


def format_report(report: Report) -> str:
    lines: list[str] = []
    lines.append(f"seed: {'PASS' if not report.seed_problems else 'FAIL'}")
    lines.extend(f"  - {p}" for p in report.seed_problems)
    for mid, problems in report.per_meeting.items():
        lines.append(f"{mid}: {'PASS' if not problems else 'FAIL'}")
        lines.extend(f"  - {p}" for p in problems)
    for mid in report.missing:
        lines.append(f"{mid}: MISSING transcript")
    lines.append(f"cross-meeting rules: {'PASS' if not report.cross_problems else 'FAIL'}")
    lines.extend(f"  - {p}" for p in report.cross_problems)
    if report.draft_present:
        status = (
            "no findings"
            if not report.draft_problems
            else f"{len(report.draft_problems)} finding(s)"
        )
        lines.append(
            f"{LIVE_MEETING_ID} (live-demo DRAFT, reported separately, never auto-fixed): {status}"
        )
        lines.extend(f"  - {p}" for p in report.draft_problems)
    else:
        lines.append(f"{LIVE_MEETING_ID} (live-demo draft): not present")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate seed JSON and transcripts (read-only).")
    parser.add_argument("--seed-dir", type=Path, default=SEED_DIR)
    parser.add_argument("--transcripts-dir", type=Path, default=None)
    args = parser.parse_args(argv)

    from app.config import settings

    seed = load_seed(args.seed_dir)
    transcripts_dir = args.transcripts_dir or (args.seed_dir / "transcripts")
    texts = read_transcripts(seed, transcripts_dir)
    report = validate_all_texts(seed, texts, demo_today=settings.demo_today, strict_counts=True)
    print(format_report(report))
    return 0 if report.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
